/**
 * Architecture Generation flow.
 *
 * In Claudio v2 this is powered by Claude Sonnet 4.6 (via the cohere-chat
 * shim that internally routes to `@/lib/ai/claude`). The "Cohere" names in
 * this file are retained for Phase 1 to minimize consumer churn; Phase 3
 * renames everything to *WithClaude and removes the shim.
 */

import { generateCohereChatCompletion } from '@/ai/cohere-chat';
import { isClaudeConfigured } from '@/lib/ai/claude';
import { processArchitectureWithIcons } from '@/ai/middleware/architectureIconProcessor';

export interface ArchitectureGenerationInput {
  problemStatement: string;
  cloudProvider?: 'aws' | 'azure' | 'gcp';
  complexity?: 'simple' | 'medium' | 'complex';
}

export interface ArchitectureGenerationOutput {
  architectureSuggestion: string;
  rationale: string;
  provider: 'claude';
}

export async function generateArchitectureWithCohere(input: ArchitectureGenerationInput): Promise<ArchitectureGenerationOutput> {
  if (!isClaudeConfigured()) {
    throw new Error('Claude API is not configured. Set ANTHROPIC_API_KEY in .env.local (see .env.example).');
  }

  const systemPrompt = getArchitecturePrompt(input);

  try {
    const response = await generateCohereChatCompletion({
      message: input.problemStatement,
      promptContext: systemPrompt,
      temperature: 0.3,
      maxTokens: 4000,
    });

    // Parse the JSON response
    let parsedArchitecture;
    try {
      parsedArchitecture = JSON.parse(response);
    } catch (parseError) {
      // Try to extract JSON from response if it's wrapped in text
      const jsonMatch = response.match(/\{[\s\S]*\}/);
      if (jsonMatch) {
        parsedArchitecture = JSON.parse(jsonMatch[0]);
      } else {
        throw new Error('Invalid JSON response from AI');
      }
    }

    // Process the response with icon resolution
    const processedArchitecture = await processArchitectureWithIcons(parsedArchitecture, input.cloudProvider || 'aws');

    return {
      architectureSuggestion: JSON.stringify({
        nodes: processedArchitecture.nodes,
        edges: processedArchitecture.edges,
        metadata: parsedArchitecture.metadata || {},
      }),
      rationale: `Generated by Claude Sonnet 4.6 — ${processedArchitecture.iconStats?.totalNodes || 0} services with ${processedArchitecture.iconStats?.nodesWithIcons || 0} icons resolved`,
      provider: 'claude',
    };
  } catch (error) {
    // eslint-disable-next-line no-console
    console.error('Claude architecture generation failed:', error);
    throw new Error(`Architecture generation failed: ${error instanceof Error ? error.message : 'Unknown error'}`);
  }
}

/**
 * Get architecture generation prompt based on input parameters
 */
function getArchitecturePrompt(input: ArchitectureGenerationInput): string {
  const { cloudProvider = 'aws', complexity = 'medium' } = input;
  
  const cloudProviderInstructions = {
    aws: 'Use AWS services like EC2, Lambda, S3, DynamoDB, API Gateway, CloudFront, RDS, ECS, EKS, etc.',
    azure: 'Use Azure services like Virtual Machines, Functions, Blob Storage, Cosmos DB, API Management, Front Door, SQL Database, Container Instances, AKS, etc.',
    gcp: 'Use Google Cloud services like Compute Engine, Cloud Functions, Cloud Storage, Firestore, API Gateway, Cloud CDN, Cloud SQL, Cloud Run, GKE, etc.'
  };

  const complexityInstructions = {
    simple: 'Create a simple architecture with 3-5 core services focusing on basic functionality.',
    medium: 'Design a moderately complex architecture with 6-10 services including redundancy and best practices.',
    complex: 'Build a comprehensive enterprise-grade architecture with 10+ services including advanced patterns like microservices, event-driven architecture, and multi-region deployment.'
  };

  return `You are an expert cloud architect. Generate a detailed cloud architecture based on the user's requirements.

CLOUD PROVIDER: ${cloudProvider.toUpperCase()}
${cloudProviderInstructions[cloudProvider]}

COMPLEXITY LEVEL: ${complexity}
${complexityInstructions[complexity]}

REQUIREMENTS:
1. Return ONLY valid JSON in this exact format:
{
  "nodes": [
    {
      "id": "unique-id",
      "type": "aws-service",
      "position": {"x": number, "y": number},
      "data": {
        "label": "Service Name",
        "service": "AWS Service Type",
        "description": "Brief description",
        "estCost": "$X/month",
        "faultTolerance": "High/Medium/Low",
        "layer": "presentation/application/data"
      }
    }
  ],
  "edges": [
    {
      "id": "edge-id",
      "source": "source-node-id",
      "target": "target-node-id",
      "type": "smoothstep",
      "animated": true,
      "label": "Connection description"
    }
  ],
  "metadata": {
    "title": "Architecture Title",
    "description": "Architecture overview",
    "cloudProvider": "${cloudProvider}",
    "estimatedCost": "$X/month",
    "scalability": "Description of scaling approach",
    "reliability": "Description of reliability features",
    "security": "Description of security measures"
  }
}

2. Use proper ${cloudProvider.toUpperCase()} service names exactly as they appear in the console
3. Position nodes logically (presentation layer at top, data layer at bottom)
4. Include realistic cost estimates
5. Add meaningful connections between services
6. Ensure the architecture follows ${cloudProvider.toUpperCase()} best practices
7. Include proper security, monitoring, and backup considerations

Generate the architecture now:`;
}

/**
 * Legacy export for backward compatibility
 */
export const generateArchitectureWithClaude = generateArchitectureWithCohere; 